---
_extends: .github

repository:
  name: dockerfiles
  description: Dockerfiles for (cross-)compiling TokTok projects for various platforms
  topics: docker, ghc, android, windows, qt, buildfarm, bazel

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - "build (alpine-s390x)"
          - "build (bazel)"
          - "build (bazel-cache)"
          - "build (flutter-web)"
          - "build (frama-c)"
          - "build (freebsd)"
          - "build (haskell)"
          - "ci/circleci: compcert"
          - "ci/circleci: infer"
          - "CodeFactor"
          - "code-review/reviewable"
          - "ghc-base"
          - "ghc-android (aarch64)"
          - "ghc-android (arm)"
