---
version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - ghc-android-aarch64

jobs:
  ghc-android-aarch64:
    docker:
      - image: alpine:3.11.5

    steps:
      - run: apk add make perl
      - checkout
      - run: make
      - setup_remote_docker
      - run: apk add docker-cli
      - run: echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin
      - run: docker build -t toktoknet/ghc-android:latest.aarch64 ghc-android/aarch64
      - run: docker push toktoknet/ghc-android:latest.aarch64
