---
version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - ghc-base
      - ghc-android-aarch64:
          requires: [ghc-base]
      - ghc-android-arm:
          requires: [ghc-base]
      - ghc-android-i686:
          requires: [ghc-base]
      - ghc-android-x86_64:
          requires: [ghc-base]

jobs:
  ghc-base:
    docker: [{image: alpine:3.11.5}]

    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image ghc base

  ghc-android-aarch64:
    docker: [{image: alpine:3.11.5}]

    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image ghc-android aarch64

  ghc-android-arm:
    docker: [{image: alpine:3.11.5}]

    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image ghc-android arm

  ghc-android-i686:
    docker: [{image: alpine:3.11.5}]

    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image ghc-android i686

  ghc-android-x86_64:
    docker: [{image: alpine:3.11.5}]

    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image ghc-android x86_64
