---
version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - builder
      - buildfarm-base
      - buildfarm-server:
          requires: [buildfarm-base]
      - buildfarm-worker:
          requires: [builder, buildfarm-base]
      - ghc-base
      - ghc-android-aarch64:
          requires: [ghc-base]
      - ghc-android-arm:
          requires: [ghc-base]
      - ghc-android-i686:
          requires: [ghc-base]
      - ghc-android-x86_64:
          requires: [ghc-base]

jobs:
  ##################################################
  #
  # :: Bazel docker-sandbox and buildfarm images
  #
  ##################################################

  builder:
    docker: [{image: alpine:3.11.5}]

    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image buildfarm/builder toxchat/builder:1.0.0

  buildfarm-base:
    docker: [{image: alpine:3.11.5}]

    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image buildfarm/base toxchat/buildfarm-base:1.0.0

  buildfarm-server:
    docker: [{image: alpine:3.11.5}]

    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image buildfarm/server toxchat/buildfarm-server:1.0.0

  buildfarm-worker:
    docker: [{image: alpine:3.11.5}]

    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image buildfarm/worker toxchat/buildfarm-worker:1.0.0

  ##################################################
  #
  # :: GHC for Android
  #
  ##################################################

  ghc-base:
    docker: [{image: alpine:3.11.5}]

    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image ghc/base toktoknet/ghc:8.6.5

  ghc-android-aarch64:
    docker: [{image: alpine:3.11.5}]

    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image ghc-android/aarch64 toktoknet/ghc-android:8.6.5.aarch64

  ghc-android-arm:
    docker: [{image: alpine:3.11.5}]

    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image ghc-android/arm toktoknet/ghc-android:8.6.5.arm

  ghc-android-i686:
    docker: [{image: alpine:3.11.5}]

    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image ghc-android/i686 toktoknet/ghc-android:8.6.5.i686

  ghc-android-x86_64:
    docker: [{image: alpine:3.11.5}]

    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image ghc-android/x86_64 toktoknet/ghc-android:8.6.5.x86_64
