---
version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - compcert
      - infer

jobs:
  ##################################################
  #
  # :: Static analysis images
  #
  ##################################################

  compcert:
    docker: [{ image: alpine:3.11.5 }]

    steps:
      - run: apk add git openssh-client
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image compcert toxchat/compcert:latest

  infer:
    docker: [{ image: alpine:3.11.5 }]

    steps:
      - run: apk add git openssh-client
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image infer toxchat/infer:latest
