---
version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - builder
      - buildfarm-base
      - buildfarm-server:
          requires: [buildfarm-base]
      - buildfarm-worker:
          requires: [builder, buildfarm-base]
# Disabled GHC for now, because we're not actively developing it and it takes
# hours to build these.
#     - ghc-base
#     - ghc-android-aarch64:
#         requires: [ghc-base]
#     - ghc-android-arm:
#         requires: [ghc-base]
#     - ghc-android-i686:
#         requires: [ghc-base]
#     - ghc-android-x86_64:
#         requires: [ghc-base]

jobs:
  ##################################################
  #
  # :: Bazel docker-sandbox and buildfarm images
  #
  ##################################################

  builder:
    docker: [{image: alpine:3.11.5}]

    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image buildfarm builder

  buildfarm-base:
    docker: [{image: alpine:3.11.5}]

    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image buildfarm buildfarm-base

  buildfarm-server:
    docker: [{image: alpine:3.11.5}]

    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image buildfarm buildfarm-server

  buildfarm-worker:
    docker: [{image: alpine:3.11.5}]

    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image buildfarm buildfarm-worker

  ##################################################
  #
  # :: GHC for Android
  #
  ##################################################

  ghc-base:
    docker: [{image: alpine:3.11.5}]

    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image ghc base

  ghc-android-aarch64:
    docker: [{image: alpine:3.11.5}]

    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image ghc-android aarch64

  ghc-android-arm:
    docker: [{image: alpine:3.11.5}]

    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image ghc-android arm

  ghc-android-i686:
    docker: [{image: alpine:3.11.5}]

    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image ghc-android i686

  ghc-android-x86_64:
    docker: [{image: alpine:3.11.5}]

    steps:
      - checkout
      - setup_remote_docker
      - run: .circleci/build-image ghc-android x86_64
