---
name: docker

on:
  push:
    branches: [master]
  #pull_request:
    #branches: [master]

jobs:
  freebsd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build freebsd image
        shell: 'script -q -e -c "bash {0}"'
        run: make -C freebsd build
      - name: Push images to DockerHub
        if: github.event_name == 'push'
        run: docker push toxchat/freebsd:latest
